import PyQt5.QtGui as QtGui
from PyQt5.QtCore import Qt


WINDOW_OPACITY = 0.99
WINDOW_BG = QtGui.QColor('#28303b')
WINDOW_DROPSHADOW_COLOR = QtGui.QColor(0, 0, 0, 120)
WINDOW_DROPSHADOW_RADIUS = 20
WINDOW_ROUND_RADIUS = 20

WINDOW_DRAG_ZONE_HEIGHT = 35
WINDOW_TOOL_BTN_SIZE = 25

WINDOW_TOOL_BTN_BG = QtGui.QColor(255, 255, 255, 230)
WINDOW_TOOL_BTN_FG = QtGui.QColor(30, 30, 30)
WINDOW_TOOL_BTN_FG_ACTIVE = Qt.white

WINDOW_TOOL_BTN_CLOSE_BG_HOVER = QtGui.QColor('#e46565')
WINDOW_TOOL_BTN_PIN_BG_HOVER = QtGui.QColor('#a6c7de')
WINDOW_TOOL_BTN_PIN_BG_CHECKED = QtGui.QColor('#65b3e4')
WINDOW_TOOL_BTN_PRO_BG_HOVER = QtGui.QColor('#ded5a6')
WINDOW_TOOL_BTN_PRO_BG_CHECKED = QtGui.QColor('#e89f48')

KEYBOARD_BG_DEFAULT = QtGui.QColor('#313946')
KEYBOARD_BG_HOVER = QtGui.QColor('#404853')
KEYBOARD_FG_DEFAULT = QtGui.QColor(255, 255, 255, 200)

KEY_DEFAULT_FONTSIZE = 24
KEY_EVAL_BG_DEFAULT = QtGui.QColor('#9cbc7b')
KEY_EVAL_BG_HOVER = QtGui.QColor('#a6b892')
# KEY_DANGER_BG_HOVER = QtGui.QColor('#eb6b65')
KEY_DANGER_BG_HOVER = QtGui.QColor('#a24952')
KEY_SPECIAL_BG_HOVER = QtGui.QColor('#434f5c')

KEY_SIZE_STD = 80
KEY_WIDTH_PRO = 70
KEY_HEIGHT_PRO = 50